### ISSUE TITLE
Tag the schema

### ISSUE THREAD

**Issue by fabaff** [SpaceApi/schema#100]
Please tag the source instead of adding a new file for a new version. This would make it much easier to see what was changed without using a diff tool. 

Thanks

**Comment by rnestler** [comment]
We want to have multiple schemas, since it is possible to be compliant with multiple versions of the API.  See https://validator.spaceapi.io/ui/?url=https://port39.de/spaceapi.json for example.

That said: It is possible to see what changed just by looking at the history of the schema files: https://github.com/SpaceApi/schema/commits/master/14.json. Since we copy the files after a release to start the new version one can see the full history / diff since the copy: https://github.com/SpaceApi/schema/commits/6acb9ac2e6d6fe78c8190ef0d8a1a8d915c59857/14-draft.json?browsing_rename_history=true&new_path=14.json&original_branch=master

But I agree: It would still have value to have tags at the various release times to make it easier to see the diff between two versions.

**Comment by dbrgn** [comment]
> But I agree: It would still have value to have tags at the various release times to make it easier to see the diff between two versions.

How would you see the diff if the two files have different filenames? Additionally, sometimes we upgrade the JSON schema version, which can introduce very hard-to-diff changes. JSON schema is not optimized for diffing.

In any case, the main "diff" between versions is now our restructured CHANGELOG (since #89), so I think this can be closed.
